golang : update v1.15.3
coolsnowwolf/packages pull request #98
Opened 2020-10-18 17:21 UTC by Beginner-Go

V2ray-core V4.31.2 Dependencies to upgrade

Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

2020-10-22 08:10 UTC, Mattraks requested changes

2020-10-22 08:10 UTC, Mattraks commented on lang/golang/golang/Makefile
> +GO_SOURCE_URLS:=https://golang.org/dl/
这个没必要改
https://golang.org/dl/
会重定向到
https://dl.google.com/go/

2020-10-22 08:46 UTC, Beginner-Go commented on lang/golang/golang/Makefile
> +GO_SOURCE_URLS:=https://golang.org/dl/
https://dl.google.com/go/我也没删除，只是加了个域名 没关系吧？

2020-10-22 08:48 UTC, Mattraks commented on lang/golang/golang/Makefile
> +GO_SOURCE_URLS:=https://golang.org/dl/
其实是没有意义啊

2020-10-22 10:51 UTC, Beginner-Go commented on lang/golang/golang/Makefile
> +GO_SOURCE_URLS:=https://golang.org/dl/
好的 已更正 谢谢提醒

2020-11-24 02:15 UTC, Mattraks commented on lang/golang/golang/Makefile
> +                https://golang.org/dl/
这个不是实际地址,该地址会重定向到第一条,添加这个没有意义还不如添加镜像
https://gomirrors.org/dl/go/

2020-11-24 03:26 UTC, Beginner-Go commented on lang/golang/golang/Makefile
> +                https://golang.org/dl/
> 这个不是实际地址,该地址会重定向到第一条,添加这个没有意义还不如添加镜像
> https://gomirrors.org/dl/go/

已更正 谢提醒

2020-11-24 07:07 UTC, Mattraks approved these changes

2020-11-24 08:58 UTC, Mattraks commented on lang/golang/golang/Makefile
> +                https://golang.org/dl/
缺少补丁文件
[patches](https://github.com/openwrt/packages/blob/master/lang/golang/golang/patches/001-allow-flags-in-CGO_LDFLAGS-environment-variable-not-in-security-allowlist-GH-42567.patch)

2020-11-24 09:46 UTC, Mattraks commented on lang/golang/golang/Makefile
> +                https://golang.org/dl/
建议同步官方
[golang](https://github.com/openwrt/packages/tree/master/lang/golang)

2020-11-25 13:29 UTC, Beginner-Go commented on lang/golang/golang/Makefile
> +                https://golang.org/dl/
已同步上游

2020-11-30 14:50 UTC, closed without merging